### ISSUE TITLE
Create state diagram of chat flow.

### ISSUE THREAD

**Issue by p16i** [youpin-city/youpin-bot#27]
It would be good to have this diagram so that one can easily understand and be able to test the bot.

This tool might be useful : https://www.draw.io

**Comment by supasate** [comment]
Definitely agree.

**Comment by tvirot** [comment]
Here's a link to the diagram: https://drive.google.com/file/d/0B0seIkVGhqYCMkhBeEZEX3dSSGM/view?usp=sharing

Will also update the readme.
