### ISSUE TITLE
Remove duplicate tags

### ISSUE THREAD

**Issue by puripant** [youpin-city/youpin-bot#9]
This can happen when the user adds a category in the pin description and chooses the same category again when asked. Even better if tags of the same meaning can be grouped into one: ฟุตบาท/ทางเท้า/footpath

![img_2220](https://cloud.githubusercontent.com/assets/115980/17093146/af5059a0-5271-11e6-84bc-cbb88d7735bf.PNG)
![img_2221](https://cloud.githubusercontent.com/assets/115980/17093148/afbe0b3a-5271-11e6-8644-8a95ad272c96.PNG)

**Comment by tvirot** [comment]
@rapee, do you want to handle this on your end?

**Comment by rapee** [comment]
Should this be done on API?

**Comment by supasate** [comment]
API should handle it.

**Comment by supasate** [comment]
As discussed, youpin-web will handle it. See youpin-city/youpin-web#9.

**Comment by p16i** [comment]
Can we close this issue?

**Comment by tvirot** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10117671-117823830_6-s4-v1.png?transparent=1&width=246)
